# Generated by Django 5.2.17 on 2026-08-29 06:00

import apps.bookings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(primary_key=True, serialize=False)),
                ('is_open_for_booking', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_user_id', models.ForeignKey(blank=True, help_text="The Museum Manager who last changed this date's state -- set on every change, open or close, not only on close.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'date_availability',
                'ordering': ['visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.TextField(default=apps.bookings.models._generate_reference, unique=True)),
                ('category_name_en', models.TextField()),
                ('category_name_am', models.TextField()),
                ('unit_price_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('visit_date', models.DateField()),
                ('booking_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], max_length=10)),
                ('group_name', models.TextField(blank=True, null=True)),
                ('group_contact_phone', models.TextField(blank=True, null=True)),
                ('booked_quantity', models.PositiveIntegerField()),
                ('attended_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('pending_approval', 'Pending approval'), ('pending', 'Pending'), ('visited', 'Visited'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='awaiting_payment', max_length=20)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], max_length=10, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rescheduled_count', models.PositiveSmallIntegerField(default=0)),
                ('notice_sent_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('chapa_checkout_url', models.TextField(blank=True, null=True)),
                ('receipt_url', models.TextField(blank=True, null=True)),
                ('settled', models.BooleanField(default=False)),
                ('settlement_transfer_id', models.UUIDField(blank=True, null=True)),
                ('approved_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.category')),
                ('checked_in_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(db_column='visitor_id', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'visit_date'], name='booking_status_visit_date_idx'), models.Index(condition=models.Q(('settled', False), ('status', 'visited')), fields=['id'], name='booking_unsettled_visited_idx'), models.Index(condition=models.Q(('notice_sent_at__isnull', False), ('status', 'pending')), fields=['notice_sent_at'], name='booking_pending_notice_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('booked_quantity__gte', 1)), name='booking_quantity_at_least_one'), models.CheckConstraint(condition=models.Q(('attended_quantity__isnull', True), models.Q(('attended_quantity__gte', 0), ('attended_quantity__lte', models.F('booked_quantity'))), _connector='OR'), name='booking_attended_within_booked'), models.CheckConstraint(condition=models.Q(('booking_type', 'individual'), ('group_name__isnull', False), _connector='OR'), name='booking_group_requires_group_name'), models.CheckConstraint(condition=models.Q(('booking_type', 'group'), ('approval_status__isnull', True), _connector='OR'), name='booking_approval_status_only_for_group'), models.CheckConstraint(condition=models.Q(('rescheduled_count__lte', 1)), name='booking_rescheduled_at_most_once')],
            },
        ),
    ]
