# Generated by Django 5.2.17 on 2026-08-30 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalog', '0002_seed_categories'),
        ('settlement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_unsettled_visited_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='settled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='settlement_transfer_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='ifmis_voucher_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='settlement.cashierreconciliation'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(condition=models.Q(('reconciliation__isnull', True), ('status', 'visited')), fields=['checked_in_by_user_id'], name='booking_visited_unrecon_idx'),
        ),
    ]
