# Generated by Django 5.2.17 on 2026-09-04 09:05
#
# Hand-edited after generation to add `_migrate_pending_approval_bookings`
# (see its docstring): the group-approval workflow (FR-BOOK-003) is being
# removed everywhere, and `pending_approval` is not a value the `status`
# CharField's `choices` will accept once this migration finishes.
# `choices` isn't a DB-level constraint in Postgres, so this wouldn't fail
# loudly on its own -- but leaving stale `pending_approval` rows behind
# would silently orphan them (no more manager screen to act on them, and
# every `status`-based query/filter elsewhere in the codebase no longer
# expects that value), so migrate the data explicitly instead of relying
# on it happening to not matter.

from django.db import migrations, models


def _migrate_pending_approval_bookings(apps, schema_editor):
    """Group bookings had no other way to reach a Museum-Manager decision
    than this now-removed status -- treat every one of them the same way
    a freshly-created booking is treated post-removal: `awaiting_payment`,
    ready for the group leader to pay. This only ever matches rows written
    before this migration runs; `create_booking` (apps.bookings.services)
    stops producing `pending_approval` the moment this ships."""
    Booking = apps.get_model("bookings", "Booking")
    Booking.objects.filter(status="pending_approval").update(status="awaiting_payment")


def _noop_reverse(apps, schema_editor):
    # Deliberately irreversible in substance: once `approval_status` is
    # dropped later in this same migration there is no data left to tell
    # a reversed `pending_approval` row apart from one that was always
    # `awaiting_payment`. A no-op (rather than raising) still lets
    # `migrate bookings 0003` succeed for the fields/constraint below,
    # which *are* cleanly reversible.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_seed_daily_job_schedule'),
    ]

    operations = [
        migrations.RunPython(
            _migrate_pending_approval_bookings, _noop_reverse
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_approval_status_only_for_group',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='approved_by_user_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('pending', 'Pending'), ('visited', 'Visited'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='awaiting_payment', max_length=20),
        ),
    ]
