# Generated by Django 5.2.17 on 2026-09-05 18:52
#
# Hand-edited after generation to add `_backfill_group_tin_for_existing_
# group_bookings` (see its docstring): `booking_group_requires_group_tin`
# below would otherwise fail this migration outright on any environment
# that already has a group `Booking` row predating this field (every one
# of them has `group_tin IS NULL` by construction, since the column
# didn't exist yet) -- mirrors 0004's identical
# `_migrate_pending_approval_bookings` precedent for the same class of
# problem (a new, stricter constraint colliding with pre-existing rows).

from django.conf import settings
from django.db import migrations, models

# Sentinel for a group booking that predates this field and has no real
# TIN on file -- distinguishable at a glance from an actual TIN (which is
# only ever digits) by staff reconciling later, and by
# `_noop_reverse`/support tooling if this ever needs to be found and
# followed up on.
_UNKNOWN_TIN_PLACEHOLDER = "UNKNOWN"


def _backfill_group_tin_for_existing_group_bookings(apps, schema_editor):
    """Every group `Booking` written before this migration has no
    `group_tin` at all (the column didn't exist) -- give each one the
    placeholder above rather than leaving it `NULL`, which
    `booking_group_requires_group_tin` (added later in this same
    migration) would otherwise reject. Real bookings created after this
    migration ships always get a real TIN, since `create_booking`
    requires it for `booking_type='group'` from this point on."""
    Booking = apps.get_model("bookings", "Booking")
    Booking.objects.filter(booking_type="group", group_tin__isnull=True).update(
        group_tin=_UNKNOWN_TIN_PLACEHOLDER
    )


def _noop_reverse(apps, schema_editor):
    # Deliberately irreversible in substance, same reasoning as 0004's
    # own `_noop_reverse`: once the constraint below is dropped by a
    # reverse migration there is no correctness reason to also blank out
    # `group_tin` again, and no way to tell a backfilled placeholder
    # apart from a real TIN that happens to read "UNKNOWN" anyway. A
    # no-op still lets `migrate bookings 0006` succeed for the field/
    # constraint below, which *are* cleanly reversible.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_items'),
        ('settlement', '0002_cashierreconciliation_transfer_receipt_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='group_tin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(
            _backfill_group_tin_for_existing_group_bookings, _noop_reverse
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('booking_type', 'individual'), ('group_tin__isnull', False), _connector='OR'), name='booking_group_requires_group_tin'),
        ),
    ]
