# Generated by Django 5.2.17 on 2026-09-07 00:00
#
# Adds per-category attendance to `BookingItem` (FR-REFUND-002 fix):
# `apps.refunds.services.compute_refundable_amount` previously had no way
# to know *which* category a partial-attendance shortfall belonged to on
# a mixed-category booking, and fell back to refunding a blended average
# price across every category on the booking -- wrong whenever the
# no-shows and the still-present categories aren't priced the same (e.g.
# 3 Adult + 4 Student booked, 2 Students absent: the correct refund is
# `2 * student_price`, not `2 * blended_average_price`). This field is
# what lets that computation use each item's own `unit_price_etb`
# instead. No backfill: a `BookingItem` on a booking already `Visited`
# before this migration ships has no way to recover which category its
# no-shows belonged to (`Booking.attended_quantity` only ever recorded
# one combined total) -- those rows stay `NULL` on every item forever,
# and `compute_refundable_amount` falls back to the old blended-average
# calculation for exactly that case, never for a booking checked in
# after this ships.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_group_tin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='attended_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('attended_quantity__isnull', True),
                )
                | models.Q(
                    ('attended_quantity__gte', 0),
                    ('attended_quantity__lte', models.F('quantity')),
                ),
                name='booking_item_attended_within_quantity',
            ),
        ),
    ]
