# Generated by Django 5.2.17 on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_flagged_mismatch_at_and_more'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='institutions.institution'),
        ),
    ]
