# Generated by Django 5.2.17 on 2026-09-24
"""
UAT round 1: one-off backfill for `apps.institutions.Institution`, run
once as this app is introduced. Every group `Booking` made before this
migration has only its own `group_name`/`group_tin` text fields, with no
shared record behind either -- this migration creates one `Institution`
row per distinct normalized TIN found among them, and points every
matching `Booking.institution` at it, so historical bookings benefit from
the same "one canonical institution per TIN" guarantee a booking made
after this migration gets from `apps.institutions.services.
resolve_institution` at booking time.

Deliberately re-implements TIN normalization inline (see `normalize_tin`
below) rather than importing `apps.institutions.services.normalize_tin`
-- a migration's own logic must stay frozen at the moment it runs, not
silently pick up a later edit to that function; this is the standard
Django reason migrations use `apps.get_model(...)` historical models
instead of a live import, applied here to a plain function too.

A `group_tin` that doesn't normalize to exactly 10 digits (some
historical rows predate any format enforcement at all -- inconsistent
spacing, wrong length, stray characters) is left with `institution` NULL
rather than guessed at or coerced; `Booking.institution`'s own field
comment already documents that not every group booking has one.

Reverse is a no-op (`RunPython.noop`): unwinding this would mean either
deleting `Institution` rows that a booking made *after* this migration
ran may have since resolved to and built real history against, or
silently detaching that history -- both are worse than leaving the
backfilled data in place if this migration is ever rolled back.
"""

import re

from django.db import migrations

TIN_LENGTH = 10


def normalize_tin(raw_tin):
    """Frozen copy of `apps.institutions.services.normalize_tin` at the
    moment this migration was written -- see the module docstring above
    for why this isn't a live import. Returns `None` (not an exception)
    for a TIN that doesn't normalize cleanly; there is no request to
    reject here, only historical data to skip.
    """
    if not raw_tin:
        return None
    cleaned = re.sub(r"[\s\-]", "", str(raw_tin))
    if re.fullmatch(r"\d{%d}" % TIN_LENGTH, cleaned):
        return cleaned
    return None


def backfill_institutions(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    Institution = apps.get_model("institutions", "Institution")
    AuditLogEntry = apps.get_model("core", "AuditLogEntry")

    group_bookings = Booking.objects.filter(
        booking_type="group", group_tin__isnull=False
    ).order_by("created_at")

    # One Institution per normalized TIN, named after the *most recent*
    # booking using that TIN -- the same "freshest typed name wins" rule
    # `services.resolve_institution` applies going forward (Section 8's
    # decision #3), applied here as "last write, in booking order, wins"
    # since there's no live booker interaction to ask.
    by_tin = {}
    for booking in group_bookings:
        normalized = normalize_tin(booking.group_tin)
        if normalized is None:
            continue
        by_tin.setdefault(normalized, []).append(booking)

    for normalized_tin, bookings in by_tin.items():
        latest = bookings[-1]
        institution = Institution.objects.create(
            tin=normalized_tin,
            name=latest.group_name or normalized_tin,
            created_by_user_id=None,
        )
        Booking.objects.filter(id__in=[b.id for b in bookings]).update(
            institution=institution
        )
        AuditLogEntry.objects.create(
            actor_id=None,
            action="institution.backfilled",
            target_type="institution",
            target_id=str(institution.id),
            metadata={
                "tin": normalized_tin,
                "name": institution.name,
                "booking_count": len(bookings),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_institution'),
    ]

    operations = [
        migrations.RunPython(backfill_institutions, migrations.RunPython.noop),
    ]
