# Generated by Django 5.2.17 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_backfill_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ifmis_document_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
