# Generated by Django 5.2.17 on 2026-08-29 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('visitor_otp', 'Visitor OTP'), ('visitor_email_verification', 'Visitor email verification'), ('staff_password_reset', 'Staff password reset'), ('booking_payment_confirmed', 'Booking payment confirmed'), ('no_show_notice', 'No-show notice'), ('refund_confirmed', 'Refund confirmed'), ('reschedule_confirmed', 'Reschedule confirmed'), ('group_booking_decided', 'Group booking decided')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(db_column='account_id', help_text='The recipient.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, db_column='booking_id', help_text='Nullable -- most notifications are booking-related, but not necessarily all (e.g. visitor_otp, staff_password_reset).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=5)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_delivery',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['account'], name='notification_account_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['booking'], name='notification_booking_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification'], name='notif_delivery_notif_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='notification_delivery_unique_channel'),
        ),
    ]
