# Generated by Django 5.2.17 on 2026-09-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('visitor_otp', 'Visitor OTP'), ('visitor_email_verification', 'Visitor email verification'), ('staff_password_reset', 'Staff password reset'), ('booking_payment_confirmed', 'Booking payment confirmed'), ('no_show_notice', 'No-show notice'), ('refund_confirmed', 'Refund confirmed'), ('reschedule_confirmed', 'Reschedule confirmed')], max_length=40),
        ),
    ]
