# Generated by Django 5.2.17 on 2026-08-28 20:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.TextField()),
                ('name_am', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_free', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['name_en'],
                'indexes': [models.Index(fields=['active'], name='category_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_etb__gte', 0)), name='category_price_non_negative')],
            },
        ),
    ]
