# Generated by Django 5.2.17 on 2026-09-24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_am', models.TextField(blank=True, null=True)),
                ('tin', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'app_label': 'institutions',
            },
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.CheckConstraint(check=models.Q(('tin__isnull', True), ('tin__regex', '^\\d{10}$'), _connector='OR'), name='institution_tin_is_ten_digits'),
        ),
    ]
