# Generated by Django 5.2.17 on 2026-08-29 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_ref', models.TextField(unique=True)),
                ('gateway', models.CharField(choices=[('chapa', 'Chapa')], default='chapa', max_length=10)),
                ('amount_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=8)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=10)),
                ('checkout_url', models.TextField(blank=True, null=True)),
                ('webhook_payload', models.JSONField(blank=True, null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='payment_booking_idx'), models.Index(fields=['status'], name='payment_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_etb__gt', 0)), name='payment_amount_positive')],
            },
        ),
    ]
