# Generated by Django 5.2.17 on 2026-08-29 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aggregator_fee_etb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(choices=[('cancellation', 'Cancellation'), ('partial_shortfall', 'Partial shortfall'), ('no_response', 'No response')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('chapa_refund_reference', models.TextField(blank=True, null=True)),
                ('deducted_in_transfer_id', models.UUIDField(blank=True, null=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='bookings.booking')),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='refund_booking_idx'), models.Index(fields=['status'], name='refund_status_idx'), models.Index(condition=models.Q(('deducted_in_transfer_id__isnull', True), ('status', 'completed')), fields=['id'], name='refund_undeducted_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_etb__gt', 0)), name='refund_amount_positive'), models.CheckConstraint(condition=models.Q(('aggregator_fee_etb__gte', 0)), name='refund_aggregator_fee_non_negative')],
            },
        ),
    ]
