# Generated by Django 5.2.17 on 2026-08-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='deducted_in_transfer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settlement.cashierreconciliation'),
        ),
    ]
