# Generated by Django 5.2.17 on 2026-09-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_alter_refund_deducted_in_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(choices=[('cancellation', 'Cancellation'), ('partial_shortfall', 'Partial shortfall'), ('no_response', 'No response'), ('category_correction', 'Category correction')], max_length=20),
        ),
    ]
