# Generated by Django 5.2.17 on 2026-08-30 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierReconciliation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chapa_transfer_reference', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cashier_reconciliation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cashier'], name='cashier_recon_cashier_idx'), models.Index(fields=['status'], name='cashier_recon_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_etb__gt', 0)), name='cashier_reconciliation_amount_positive')],
            },
        ),
    ]
