# Generated by Django 5.2.17 on 2026-08-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierreconciliation',
            name='transfer_receipt_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
