/**
 * Thin fetch wrapper around the API.
 *
 * NEXT_PUBLIC_API_URL points at the real Django backend (docker-compose.yml
 * -> api, on :8000) by default, since backend/ lives alongside this app in
 * the same repo. For UI-only work without the full Django/Postgres/Celery
 * stack running, point it at the optional Prism mock instead (see
 * .env.example and the root docker-compose.yml's `mock` profile).
 *
 * Request/response types come from src/lib/api-types.ts, generated by
 * `npm run generate-types` from ../contracts/openapi.yaml (repo root) — run
 * that after the backend side of this repo regenerates the contract
 * (backend/scripts/export_contract.sh).
 *
 * Per Design Spec Sec 7.2: server state (bookings, payments, receipts —
 * anything owned by the API) is managed with React Query, not global client
 * state. No client ever treats its own state as authoritative for a
 * booking's status — the API's response is always what the UI trusts. This
 * client is the single place that knows the base URL and attaches the JWT
 * access token; React Query hooks in each features/ folder call through it.
 */

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export async function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${API_URL}/api/v1${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...init?.headers,
    },
  });

  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new Error(body?.error?.message ?? `Request failed: ${res.status}`);
  }

  return res.json() as Promise<T>;
}
