/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/staff/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `GET /admin/staff` and `POST /admin/staff` -- both Platform Admin
         *     only (FR-ACC-002).
         */
        get: operations["v1_admin_staff_list"];
        put?: never;
        /**
         * @description `GET /admin/staff` and `POST /admin/staff` -- both Platform Admin
         *     only (FR-ACC-002).
         */
        post: operations["v1_admin_staff_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * @description `PUT /admin/staff/{id}` and `DELETE /admin/staff/{id}` -- both
         *     Platform Admin only (FR-ACC-002). No `GET` here: Document 04 has no
         *     single-staff-account retrieve endpoint, only the list at
         *     `/admin/staff` (mirrors `apps.catalog.CategoryDetailView`).
         */
        put: operations["v1_admin_staff_update"];
        post?: never;
        /**
         * @description `PUT /admin/staff/{id}` and `DELETE /admin/staff/{id}` -- both
         *     Platform Admin only (FR-ACC-002). No `GET` here: Document 04 has no
         *     single-staff-account retrieve endpoint, only the list at
         *     `/admin/staff` (mirrors `apps.catalog.CategoryDetailView`).
         */
        delete: operations["v1_admin_staff_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /auth/forgot-password -- Staff only (FR-ACC-006). Always 200;
         *     see services.request_password_reset for why.
         */
        post: operations["v1_auth_forgot_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/login -- Staff only (FR-ACC-002, FR-ACC-005). */
        post: operations["v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /auth/logout -- clears the refresh-token cookie so the browser
         *     stops presenting it. Note: this does not blacklist the token
         *     server-side -- SIMPLE_JWT.BLACKLIST_AFTER_ROTATION=True already assumes
         *     that, but `rest_framework_simplejwt.token_blacklist` isn't in
         *     INSTALLED_APPS (config/settings/base.py), so today every rotation's
         *     `refresh.blacklist()` call is silently swallowed (simplejwt only
         *     defines that method when the app is installed, and the rotation code
         *     catches the resulting AttributeError). Worth installing + migrating
         *     that app separately so old refresh tokens are actually invalidated,
         *     not just no-longer-cookied on this device.
         */
        post: operations["v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /auth/refresh/ -- mounted at the root urlconf (config/urls.py),
         *     shared by both credential paths (Sec 4.1).
         *
         *     Reads the refresh token from the httpOnly cookie set by `_auth_response`
         *     above instead of requiring it in the request body -- the frontend never
         *     holds or sends the refresh token itself (cookies.py). Re-sets the
         *     cookie with the rotated token on success, per SIMPLE_JWT's
         *     ROTATE_REFRESH_TOKENS.
         */
        post: operations["v1_auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/reset-password -- Staff only (FR-ACC-006). */
        post: operations["v1_auth_reset_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/visitor/verify/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /auth/visitor/verify/confirm -- completes Visitor verification
         *     and issues the same token pair Staff login does (Sec 4.1).
         */
        post: operations["v1_auth_visitor_verify_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/visitor/verify/email/{token}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /auth/visitor/verify/email/{token} -- the secondary/fallback
         *     verification channel (Sec 4.1 step 2). Opening this link marks
         *     `email_verified_at` but never issues a session on its own; only the
         *     OTP path above does that.
         */
        get: operations["v1_auth_visitor_verify_email_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/visitor/verify/start/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /auth/visitor/verify/start (FR-ACC-001, FR-ACC-003, FR-ACC-004).
         *     Used for both a first-time booking and a returning Visitor looking up
         *     their history -- there is no separate "login" for a Visitor.
         */
        post: operations["v1_auth_visitor_verify_start_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /availability -- public (FR-BOOK-008). */
        get: operations["v1_availability_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability/{date}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description PUT /availability/{date} -- Museum Manager only (FR-BOOK-008). */
        put: operations["v1_availability_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /bookings (Staff only) and POST /bookings (Visitor only,
         *     FR-BOOK-001/FR-BOOK-003).
         */
        get: operations["listBookings"];
        put?: never;
        /**
         * @description GET /bookings (Staff only) and POST /bookings (Visitor only,
         *     FR-BOOK-001/FR-BOOK-003).
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /bookings/{id} -- the owning Visitor or any Staff member. */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /bookings/{id}/cancel -- FR-BOOK-005/006. */
        post: operations["v1_bookings_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/category-correction/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description PATCH /bookings/{id}/category-correction -- Cashier only
         *     (ID-verification addendum to Document 02 Sec 2.2).
         *
         *     Corrects a booking's category when the visitor's ID at the gate
         *     doesn't match what they booked under, then either reopens payment
         *     for the difference (undercharge) or issues a refund for the
         *     difference (overcharge). Lives here, not in `apps.entrance` -- even
         *     though it's a gate-side, Cashier-only action -- because this is where
         *     that composition with `apps.payments`/`apps.refunds` already happens
         *     (`BookingListCreateView.post`/`BookingCancelView` above); `entrance`
         *     depends on `bookings` only, with no dependency of its own on
         *     `refunds`/`payments` (`apps.entrance.services`' own module
         *     docstring), so putting this endpoint there would violate that
         *     boundary. See `services.correct_booking_category`'s own docstring for
         *     the full rationale.
         */
        patch: operations["v1_bookings_category_correction_partial_update"];
        trace?: never;
    };
    "/api/v1/bookings/{id}/check-in/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /bookings/{id}/check-in -- Cashier only
         *     (FR-TICKET-001 - FR-TICKET-003, FR-TICKET-005).
         *
         *     Returns `CheckInResponseSerializer`, not the plain `BookingSerializer`
         *     -- the IFMIS-decision build prompt's Step 7: the response carries the
         *     extra fields the Cashier needs to key this transaction into IFMIS
         *     herself (payer name, amount in figures/words, purpose string).
         *     `services.check_in_booking`'s own business logic and return value
         *     (the `Booking` instance) are unchanged; only how the response is
         *     *serialized* differs from every other endpoint that returns a
         *     `Booking`.
         */
        post: operations["checkInBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/ifmis-voucher/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description PATCH /bookings/{id}/ifmis-voucher/ -- Cashier only, and only the
         *     same Cashier who checked this booking in (services.py enforces this,
         *     not this permission class -- it needs the specific booking, not just
         *     the role). Called after she's actually entered the transaction into
         *     IFMIS and gotten the real voucher reference back; settable once.
         */
        patch: operations["recordIfmisVoucherReference"];
        trace?: never;
    };
    "/api/v1/bookings/{id}/refund-requests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /bookings/{id}/refund-requests -- Visitor only
         *     (FR-TICKET-002, FR-REFUND-001b). Mounted under the top-level
         *     `/bookings/{id}/` path (see `apps.refunds.urls`'s
         *     `refund_request_urlpatterns`), even though `refunds` owns the
         *     business logic behind it -- mirrors how `apps.entrance`'s
         *     Cashier-facing endpoints live at `/bookings/...` despite that app
         *     owning FR-TICKET, not `apps.bookings`.
         */
        post: operations["requestPartialRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/reschedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /bookings/{id}/reschedule -- FR-BOOK-007. */
        post: operations["v1_bookings_reschedule_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/lookup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /bookings/lookup -- Cashier only (FR-TICKET-001, FR-TICKET-004).
         *
         *     Mounted under /api/v1/ (config/urls.py), not /api/v1/entrance/, since
         *     Document 04 places this at `/bookings/lookup` -- the entrance module
         *     owns the business logic (Design Spec Sec 3.2) without owning that
         *     part of the URL namespace, mirroring how `bookings` owns
         *     `/availability` despite that also not living under its own prefix.
         */
        get: operations["lookupBookingByReference"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /categories (FR-CAT-001, public, no auth) and POST /categories
         *     (FR-CAT-002, Museum Manager only).
         *
         *     GET also accepts `?active=all` -- Museum Manager only (silently
         *     ignored for anyone else, rather than erroring, so a stale link
         *     doesn't break for a Visitor) -- to include retired categories, so a
         *     Manager can find one again to reactivate it. Default behavior
         *     (active-only, cached) is unchanged for every other caller.
         */
        get: operations["v1_categories_list"];
        put?: never;
        /**
         * @description GET /categories (FR-CAT-001, public, no auth) and POST /categories
         *     (FR-CAT-002, Museum Manager only).
         *
         *     GET also accepts `?active=all` -- Museum Manager only (silently
         *     ignored for anyone else, rather than erroring, so a stale link
         *     doesn't break for a Visitor) -- to include retired categories, so a
         *     Manager can find one again to reactivate it. Default behavior
         *     (active-only, cached) is unchanged for every other caller.
         */
        post: operations["v1_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * @description PUT /categories/{id} and DELETE /categories/{id} -- both Museum
         *     Manager only (FR-CAT-002). No GET here: Document 04 has no single-
         *     category retrieve endpoint, only the list at /categories.
         */
        put: operations["v1_categories_update"];
        post?: never;
        /**
         * @description PUT /categories/{id} and DELETE /categories/{id} -- both Museum
         *     Manager only (FR-CAT-002). No GET here: Document 04 has no single-
         *     category retrieve endpoint, only the list at /categories.
         */
        delete: operations["v1_categories_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/webhooks/chapa/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /payments/webhooks/chapa/ -- AllowAny + signature check
         *     (Design Spec Sec 4.2; NFR-SEC-001). The only path that confirms a
         *     booking (FR-PAY-002) -- never the client-side `return_url` redirect.
         */
        post: operations["handleChapaWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refunds/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /refunds -- any authenticated user (Visitors see only their
         *     own; Staff can filter across all, Document 04).
         */
        get: operations["listRefunds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /reports/dashboard -- Museum Manager/Platform Admin only
         *     (FR-REPORT-001).
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /reports/summary -- Museum Manager/Platform Admin only
         *     (FR-REPORT-002).
         */
        get: operations["getReportSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlement/my-balance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /settlement/my-balance/ -- Cashier only. Her own outstanding
         *     balance (unreconciled Visited bookings minus unreconciled completed
         *     refunds) -- never a platform-wide total (IFMIS decision).
         */
        get: operations["getMyOutstandingBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlement/reconcile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /settlement/reconcile/ -- Cashier only. The one-click action:
         *     locks her outstanding bookings/refunds, creates a `PENDING`
         *     reconciliation row, and calls Chapa's Transfer API to move her
         *     balance into the university's fixed bank account. A confirm dialog on
         *     the client is sufficient before calling this (no OTP step -- already
         *     decided); this endpoint itself performs no additional confirmation.
         */
        post: operations["initiateReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlement/reconciliations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /settlement/reconciliations/ -- any authenticated Staff member.
         *     A Cashier sees only her own attempts; Museum Manager/Platform Admin
         *     see every cashier's (mirrors `apps.refunds.views.RefundListView`'s own
         *     ownership-scoping pattern).
         */
        get: operations["listReconciliations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlement/webhook/chapa-transfer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /settlement/webhook/chapa-transfer/ -- AllowAny + signature
         *     check (mirrors `apps.payments.views.ChapaWebhookView` exactly, same
         *     HMAC-SHA256-over-the-raw-body verification against
         *     `CHAPA_WEBHOOK_SECRET`). The only path that ever moves a
         *     reconciliation out of `PENDING` -- there is no client-side redirect
         *     for a bank transfer to (incorrectly) trust instead.
         */
        post: operations["handleChapaTransferWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET/PUT /users/me -- Visitor and Staff share this endpoint; there is
         *     no scoped RBAC to check beyond "is this account authenticated" (Sec 4.3).
         */
        get: operations["v1_users_me_retrieve"];
        /**
         * @description GET/PUT /users/me -- Visitor and Staff share this endpoint; there is
         *     no scoped RBAC to check beyond "is this account authenticated" (Sec 4.3).
         */
        put: operations["v1_users_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/bookings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /users/me/bookings -- FR-ACC-004. Mounted at the root URLconf
         *     (config/urls.py), not here, mirroring CurrentUserView's placement --
         *     Document 04 puts this under `/users/`, not `/bookings/`.
         */
        get: operations["listMyBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description `UserProfile` (Document 04) -- Visitor and Staff share one shape; a
         *     Visitor's password-adjacent fields are simply never populated.
         */
        Account: {
            /** Format: uuid */
            readonly id: string;
            readonly email: string;
            readonly phone: string | null;
            readonly full_name: string;
            readonly role: components["schemas"]["AccountRoleEnum"];
            readonly language_preference: components["schemas"]["LanguagePreferenceEnum"];
            readonly active: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `visitor` - Visitor
         *     * `cashier` - Cashier
         *     * `museum_manager` - Museum Manager
         *     * `platform_admin` - Platform Admin
         * @enum {string}
         */
        AccountRoleEnum: "visitor" | "cashier" | "museum_manager" | "platform_admin";
        /**
         * @description `UserUpdateRequest` -- an account may only ever edit its own
         *     contact/preference fields, never role/active/email (Sec 4.3).
         */
        AccountUpdate: {
            full_name?: string;
            phone?: string | null;
            language_preference?: components["schemas"]["LanguagePreferenceEnum"];
        };
        AuthResponse: {
            access_token: string;
            user: components["schemas"]["Account"];
        };
        /**
         * @description `Booking` (Document 04). Read-only -- every mutation goes through
         *     the Create/Cancel/Reschedule serializers below and services.py, never
         *     through this serializer directly.
         */
        Booking: {
            /** Format: uuid */
            readonly id: string;
            readonly reference: string;
            /** Format: uuid */
            readonly visitorId: string;
            /** Format: uuid */
            readonly categoryId: string;
            readonly categoryNameEn: string;
            readonly categoryNameAm: string;
            /** Format: date */
            readonly visitDate: string;
            readonly bookingType: string;
            readonly groupName: string | null;
            readonly groupContactPhone: string | null;
            readonly visitorName: string;
            readonly visitorEmail: string;
            readonly visitorPhone: string | null;
            readonly bookedQuantity: number;
            readonly attendedQuantity: number | null;
            readonly status: components["schemas"]["BookingStatusEnum"];
            readonly rescheduledCount: number;
            /** Format: date-time */
            readonly categoryCorrectedAt: string | null;
            /** Format: date-time */
            readonly noticeSentAt: string | null;
            readonly checkoutUrl: string | null;
            readonly receiptUrl: string | null;
            readonly ifmisVoucherReference: string | null;
            /** Format: uuid */
            readonly reconciliationId: string | null;
            /** Format: decimal */
            readonly totalAmountEtb: string;
            /** Format: date-time */
            readonly createdAt: string;
        };
        /**
         * @description `BookingCreateRequest` -- FR-BOOK-001 (individual), FR-BOOK-003
         *     (group). A plain Serializer, not a ModelSerializer: `visitor` is
         *     supplied by the view from `request.user`, never from the request
         *     body, and `categoryId`/`bookingType` need their own field names
         *     mapped onto services.create_booking's kwargs rather than a 1:1 model
         *     field mapping.
         */
        BookingCreate: {
            /** Format: date */
            visitDate: string;
            /** Format: uuid */
            categoryId: string;
            quantity: number;
            bookingType: components["schemas"]["BookingTypeEnum"];
            groupName?: string | null;
            groupContactPhone?: string | null;
        };
        /** @description `BookingRescheduleRequest` -- FR-BOOK-007. */
        BookingReschedule: {
            /** Format: date */
            newVisitDate: string;
        };
        /**
         * @description * `awaiting_payment` - Awaiting payment
         *     * `pending` - Pending
         *     * `visited` - Visited
         *     * `cancelled` - Cancelled
         *     * `refunded` - Refunded
         * @enum {string}
         */
        BookingStatusEnum: "awaiting_payment" | "pending" | "visited" | "cancelled" | "refunded";
        /**
         * @description * `individual` - Individual
         *     * `group` - Group
         * @enum {string}
         */
        BookingTypeEnum: "individual" | "group";
        /**
         * @description `CashierReconciliation` (per-cashier settlement transfer). Read-only
         *     -- every mutation goes through `services.initiate_reconciliation` /
         *     `confirm_reconciliation_success` / `confirm_reconciliation_failure`,
         *     never through this serializer directly.
         */
        CashierReconciliation: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly cashierId: string;
            /** Format: decimal */
            readonly amountEtb: string;
            readonly chapaTransferReference: string | null;
            readonly status: components["schemas"]["RefundStatusEnum"];
            /** Format: date-time */
            readonly initiatedAt: string | null;
            /** Format: date-time */
            readonly completedAt: string | null;
            readonly transferReceiptUrl: string | null;
            readonly failureReason: string | null;
            /** Format: date-time */
            readonly createdAt: string;
        };
        /**
         * @description `Category` (Document 04) -- FR-CAT-001. Read-only: every mutation
         *     goes through Create/Update below and services.py, never through this
         *     serializer directly.
         */
        Category: {
            /** Format: uuid */
            readonly id: string;
            readonly name_en: string;
            readonly name_am: string;
            /** Format: decimal */
            readonly price_etb: string;
            readonly is_free: boolean;
            readonly active: boolean;
        };
        /** @description `CategoryCreateRequest` -- Museum Manager only (FR-CAT-002). */
        CategoryCreate: {
            name_en: string;
            name_am: string;
            /** Format: decimal */
            price_etb: string;
            is_free?: boolean;
        };
        /**
         * @description `CategoryUpdateRequest` -- Museum Manager only (FR-CAT-002). Every
         *     field is optional since a single PUT here may only be a price change,
         *     only a retire/reactivate (`active`), or any combination.
         */
        CategoryUpdate: {
            name_en?: string;
            name_am?: string;
            /** Format: decimal */
            price_etb?: string;
            is_free?: boolean;
            active?: boolean;
        };
        /**
         * @description Chapa's Transfer (Payout) webhook payload
         *     (https://developer.chapa.co/integrations/webhooks -- `"type":
         *     "Payout"` events, e.g. `event: "payout.success"`). Only `reference`/
         *     `status` are validated here -- mirrors
         *     `apps.payments.serializers.ChapaWebhookSerializer`'s own choice to
         *     model just the two fields the service layer actually branches on and
         *     pass the rest of the payload through as-is. `reference` is the value
         *     *we* supplied when calling the Transfer API
         *     (`services.call_chapa_transfer_api` sends `str(reconciliation.id)`),
         *     which Chapa echoes back unchanged -- that's what
         *     `services.handle_chapa_transfer_webhook` looks the row up by, not
         *     `chapa_reference` (Chapa's own internal id for the transfer, stored
         *     for reference but never used as a lookup key).
         */
        ChapaTransferWebhook: {
            event?: string | null;
            reference: string;
            status?: string | null;
            chapa_reference?: string | null;
            /** Format: decimal */
            amount?: string | null;
            currency?: string | null;
        };
        /**
         * @description `ChapaWebhookPayload` (Document 04). Only `tx_ref`/`status` are
         *     validated here -- Chapa's payload carries additional fields as needed
         *     (Document 04's `additionalProperties: true`), which `services.
         *     confirm_payment_from_webhook` stores as-is in `payment.webhook_payload`
         *     (`request.data`, not `validated_data`) rather than having every field
         *     modeled here.
         */
        ChapaWebhook: {
            tx_ref: string;
            status: string;
            /** Format: decimal */
            amount?: string | null;
            currency?: string | null;
        };
        /**
         * @description `CheckInRequest` (Document 04) -- FR-TICKET-001. `attendedQuantity`
         *     may be 0 (nobody in the party showed up) but never negative; the
         *     upper bound (must not exceed bookedQuantity, FR-TICKET-005) is a
         *     cross-field business rule against the booking being checked in, not a
         *     field-level constraint this serializer can express on its own -- that
         *     check lives in services.check_in_booking.
         */
        CheckInRequest: {
            attendedQuantity: number;
        };
        /**
         * @description `Booking`, extended with the IFMIS voucher-prep fields the Cashier
         *     needs to key into IFMIS herself at the moment of check-in (per the
         *     IFMIS decision: the platform never calls IFMIS -- it only gives her
         *     the exact fields to copy in). Returned only from `POST
         *     /bookings/{id}/check-in` -- every other endpoint that returns a
         *     `Booking` keeps using the plain `BookingSerializer`, since these
         *     fields are only meaningful right after a check-in action, not as a
         *     general-purpose booking field.
         *
         *     All four are derived read-only from data `check_in_booking` already
         *     wrote (or that existed on the booking beforehand) -- nothing here
         *     changes `check_in_booking`'s own business logic or return value; this
         *     serializer only shapes its *response* representation.
         */
        CheckInResponse: {
            /** Format: uuid */
            readonly id: string;
            readonly reference: string;
            /** Format: uuid */
            readonly visitorId: string;
            /** Format: uuid */
            readonly categoryId: string;
            readonly categoryNameEn: string;
            readonly categoryNameAm: string;
            /** Format: date */
            readonly visitDate: string;
            readonly bookingType: string;
            readonly groupName: string | null;
            readonly groupContactPhone: string | null;
            readonly visitorName: string;
            readonly visitorEmail: string;
            readonly visitorPhone: string | null;
            readonly bookedQuantity: number;
            readonly attendedQuantity: number | null;
            readonly status: components["schemas"]["BookingStatusEnum"];
            readonly rescheduledCount: number;
            /** Format: date-time */
            readonly categoryCorrectedAt: string | null;
            /** Format: date-time */
            readonly noticeSentAt: string | null;
            readonly checkoutUrl: string | null;
            readonly receiptUrl: string | null;
            readonly ifmisVoucherReference: string | null;
            /** Format: uuid */
            readonly reconciliationId: string | null;
            /** Format: decimal */
            readonly totalAmountEtb: string;
            /** Format: date-time */
            readonly createdAt: string;
            readonly payerName: string;
            /** Format: decimal */
            readonly amountFigures: string;
            readonly amountWords: string;
            readonly ifmisPurpose: string;
        };
        /** @description `GET /reports/dashboard` response shape (FR-REPORT-001). */
        Dashboard: {
            /** Format: decimal */
            revenueTotalEtb: string;
            visitorCountsByCategory: {
                [key: string]: number;
            };
            groupVsIndividualSplit: components["schemas"]["GroupVsIndividualSplit"];
            statusMix: components["schemas"]["StatusMix"];
        };
        /**
         * @description `DateAvailability` (Document 04). Read-only -- every mutation goes
         *     through `DateAvailabilityUpdateSerializer` and services.py.
         */
        DateAvailability: {
            /** Format: date */
            date: string;
            isOpenForBooking: boolean;
            /** Format: uuid */
            closedByUserId: string | null;
            /** Format: date-time */
            closedAt: string | null;
        };
        /** @description `DateAvailabilityUpdateRequest` -- Museum Manager only (FR-BOOK-008). */
        DateAvailabilityUpdate: {
            isOpenForBooking: boolean;
        };
        DetailResponse: {
            detail: string;
        };
        /** @description `ForgotPasswordRequest` -- Staff only (FR-ACC-006). */
        ForgotPassword: {
            /** Format: email */
            email: string;
        };
        GroupVsIndividualSplit: {
            group: number;
            individual: number;
        };
        /**
         * @description * `en` - English
         *     * `am` - Amharic
         * @enum {string}
         */
        LanguagePreferenceEnum: "en" | "am";
        /**
         * @description `GET /settlement/my-balance/` response shape. Wraps a plain
         *     Decimal (the return value of `services.get_outstanding_balance`) --
         *     there is no model behind this endpoint, it's a computed figure, so a
         *     plain `Serializer` over a `{"balance_etb": ...}` dict is used rather
         *     than a `ModelSerializer`.
         */
        OutstandingBalance: {
            /** Format: decimal */
            readonly balanceEtb: string;
        };
        PaginatedAccountList: {
            data: components["schemas"]["Account"][];
            meta: {
                limit: number;
                offset: number;
                total: number;
            };
        };
        PaginatedBookingList: {
            data: components["schemas"]["Booking"][];
            meta: {
                limit: number;
                offset: number;
                total: number;
            };
        };
        PaginatedCashierReconciliationList: {
            data: components["schemas"]["CashierReconciliation"][];
            meta: {
                limit: number;
                offset: number;
                total: number;
            };
        };
        PaginatedCategoryList: {
            data: components["schemas"]["Category"][];
            meta: {
                limit: number;
                offset: number;
                total: number;
            };
        };
        PaginatedRefundList: {
            data: components["schemas"]["Refund"][];
            meta: {
                limit: number;
                offset: number;
                total: number;
            };
        };
        /**
         * @description `BookingCategoryCorrectionRequest` -- Cashier only (ID-verification
         *     addendum to Document 02 Sec 2.2). A plain Serializer, not a
         *     ModelSerializer, mirroring `BookingCreateSerializer` above: the
         *     single input is a new category, not a 1:1 model field mapping.
         */
        PatchedBookingCategoryCorrection: {
            /** Format: uuid */
            categoryId?: string;
        };
        /**
         * @description `IfmisVoucherUpdateRequest` -- Cashier only. The real Document
         *     No/Ref No she gets back from IFMIS after keying the check-in
         *     transaction in herself (services.record_ifmis_voucher_reference
         *     enforces the "same cashier, settable once" rule -- this serializer is
         *     field-shape validation only).
         */
        PatchedIfmisVoucherUpdate: {
            voucherReference?: string;
        };
        /**
         * @description * `daily` - daily
         *     * `weekly` - weekly
         *     * `monthly` - monthly
         *     * `yearly` - yearly
         * @enum {string}
         */
        PeriodEnum: "daily" | "weekly" | "monthly" | "yearly";
        /**
         * @description * `cancellation` - Cancellation
         *     * `partial_shortfall` - Partial shortfall
         *     * `no_response` - No response
         *     * `category_correction` - Category correction
         * @enum {string}
         */
        ReasonEnum: "cancellation" | "partial_shortfall" | "no_response" | "category_correction";
        /**
         * @description `Refund` (Document 04). Read-only -- every mutation goes through
         *     `RefundRequestCreateSerializer` and services.py, never through this
         *     serializer directly.
         */
        Refund: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly bookingId: string;
            /** Format: decimal */
            readonly amountEtb: string;
            readonly reason: components["schemas"]["ReasonEnum"];
            readonly status: components["schemas"]["RefundStatusEnum"];
            readonly chapaRefundReference: string | null;
            /** Format: date-time */
            readonly createdAt: string;
        };
        /**
         * @description `RefundRequestCreate` (Document 04) -- FR-TICKET-002/FR-REFUND-001b.
         *     `note` is free-text context supplied with a shortfall request
         *     (Document 05 Sec 3.5's `refund.note` column).
         */
        RefundRequestCreate: {
            note?: string | null;
        };
        /**
         * @description * `pending` - Pending
         *     * `completed` - Completed
         *     * `failed` - Failed
         * @enum {string}
         */
        RefundStatusEnum: "pending" | "completed" | "failed";
        /**
         * @description `GET /reports/summary` response shape (FR-REPORT-002). "Yearly"
         *     follows the organization's fiscal calendar, not Jan-Dec -- see
         *     `services.resolve_period_range`.
         */
        ReportSummary: {
            period: components["schemas"]["PeriodEnum"];
            /** Format: date */
            to: string;
            revenueByCategory: {
                [key: string]: string;
            };
            visitorCountsByGroup: {
                [key: string]: number;
            };
            /** Format: date */
            from: string;
        };
        /** @description `ResetPasswordRequest` -- Staff only (FR-ACC-006). */
        ResetPassword: {
            token: string;
            new_password: string;
        };
        /**
         * @description `StaffCreateRequest` (Document 04) -- FR-ACC-002, Platform Admin
         *     only. No `password` field: services.create_staff_account provisions
         *     the account with no usable password and sends a set-password link
         *     instead (FR-ACC-006's flow, reused).
         */
        StaffCreate: {
            /** Format: email */
            email: string;
            /** @default  */
            phone?: string;
            full_name: string;
            role: components["schemas"]["StaffRoleEnum"];
        };
        /** @description `LoginRequest` -- Staff only (FR-ACC-002, FR-ACC-005). */
        StaffLogin: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description * `cashier` - Cashier
         *     * `museum_manager` - Museum Manager
         * @enum {string}
         */
        StaffRoleEnum: "cashier" | "museum_manager";
        /**
         * @description `StaffUpdateRequest` (Document 04) -- FR-ACC-002, Platform Admin
         *     only. Every field optional so a single `PUT` can update the staff
         *     profile and role without changing the password.
         */
        StaffUpdate: {
            /** Format: email */
            email?: string;
            phone?: string | null;
            full_name?: string;
            role?: components["schemas"]["StaffRoleEnum"];
            active?: boolean;
        };
        StatusMix: {
            pending: number;
            visited: number;
            cancelled: number;
            refunded: number;
        };
        TokenRefreshResponse: {
            access: string;
        };
        /** @description `VisitorVerifyConfirmRequest`. */
        VisitorVerifyConfirm: {
            /** Format: uuid */
            verification_id: string;
            otp_code: string;
        };
        /**
         * @description `VisitorVerifyStartRequest` (Document 04) -- FR-ACC-001, FR-ACC-003.
         *     No password field exists here or anywhere in the Visitor path.
         */
        VisitorVerifyStart: {
            /** Format: email */
            email: string;
            phone: string;
            /** @default  */
            full_name?: string;
            language_preference?: components["schemas"]["LanguagePreferenceEnum"];
        };
        VisitorVerifyStartResponse: {
            /** Format: uuid */
            verification_id: string;
            otp_expires_in_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_admin_staff_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccountList"];
                };
            };
        };
    };
    v1_admin_staff_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["StaffCreate"];
                "multipart/form-data": components["schemas"]["StaffCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    v1_admin_staff_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StaffUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["StaffUpdate"];
                "multipart/form-data": components["schemas"]["StaffUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    v1_admin_staff_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_forgot_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ForgotPassword"];
                "multipart/form-data": components["schemas"]["ForgotPassword"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffLogin"];
                "application/x-www-form-urlencoded": components["schemas"]["StaffLogin"];
                "multipart/form-data": components["schemas"]["StaffLogin"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    v1_auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    v1_auth_reset_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ResetPassword"];
                "multipart/form-data": components["schemas"]["ResetPassword"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    v1_auth_visitor_verify_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitorVerifyConfirm"];
                "application/x-www-form-urlencoded": components["schemas"]["VisitorVerifyConfirm"];
                "multipart/form-data": components["schemas"]["VisitorVerifyConfirm"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    v1_auth_visitor_verify_email_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    v1_auth_visitor_verify_start_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitorVerifyStart"];
                "application/x-www-form-urlencoded": components["schemas"]["VisitorVerifyStart"];
                "multipart/form-data": components["schemas"]["VisitorVerifyStart"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorVerifyStartResponse"];
                };
            };
        };
    };
    v1_availability_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DateAvailability"][];
                };
            };
        };
    };
    v1_availability_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DateAvailabilityUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["DateAvailabilityUpdate"];
                "multipart/form-data": components["schemas"]["DateAvailabilityUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DateAvailability"];
                };
            };
        };
    };
    listBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["BookingCreate"];
                "multipart/form-data": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    v1_bookings_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    v1_bookings_category_correction_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBookingCategoryCorrection"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBookingCategoryCorrection"];
                "multipart/form-data": components["schemas"]["PatchedBookingCategoryCorrection"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    checkInBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckInRequest"];
                "multipart/form-data": components["schemas"]["CheckInRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInResponse"];
                };
            };
        };
    };
    recordIfmisVoucherReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedIfmisVoucherUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedIfmisVoucherUpdate"];
                "multipart/form-data": components["schemas"]["PatchedIfmisVoucherUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    requestPartialRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefundRequestCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["RefundRequestCreate"];
                "multipart/form-data": components["schemas"]["RefundRequestCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
        };
    };
    v1_bookings_reschedule_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingReschedule"];
                "application/x-www-form-urlencoded": components["schemas"]["BookingReschedule"];
                "multipart/form-data": components["schemas"]["BookingReschedule"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    lookupBookingByReference: {
        parameters: {
            query: {
                reference: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    v1_categories_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    v1_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryCreate"];
                "multipart/form-data": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryCreate"];
                };
            };
        };
    };
    v1_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryUpdate"];
                "multipart/form-data": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    v1_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    handleChapaWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapaWebhook"];
                "application/x-www-form-urlencoded": components["schemas"]["ChapaWebhook"];
                "multipart/form-data": components["schemas"]["ChapaWebhook"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRefunds: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRefundList"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    getReportSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"];
                };
            };
        };
    };
    getMyOutstandingBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutstandingBalance"];
                };
            };
        };
    };
    initiateReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashierReconciliation"];
                };
            };
        };
    };
    listReconciliations: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCashierReconciliationList"];
                };
            };
        };
    };
    handleChapaTransferWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChapaTransferWebhook"];
                "application/x-www-form-urlencoded": components["schemas"]["ChapaTransferWebhook"];
                "multipart/form-data": components["schemas"]["ChapaTransferWebhook"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    v1_users_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["AccountUpdate"];
                "multipart/form-data": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    listMyBookings: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBookingList"];
                };
            };
        };
    };
}
